apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oxf6jj099-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oxf6jj099-go 
  name: oxf6jj099-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oxf6jj099-go 
